apiVersion: v1
kind: Service
metadata:
  name: {{ include "db.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    pp: {{ include "db.name" . }}
