apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "db.fullname" . }}
spec:
  storageClassName: {{ .Values.persistence.classname }}
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistence.path }}

kind: PersistentVolumeClaim
metadata:
  name: {{ include "db.fullname" . }}
spec:
  storageClassName: {{ .Values.persistence.classname }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
      
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mongodb-storageclass
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
