apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "db.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
