apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "db.fullname" . }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistence.path }}

kind: PersistentVolumeClaim
metadata:
  name: {{ include "db.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
      

