replicaCount: 1

image:
  repository: ngocongbang/database
  pullPolicy: IfNotPresent
  tag: ""

service:
  port: 27017
  targetPort: 27017
  type: ClusterIP
  
persistence:
  enabled: true
  accessModes:
    - ReadWriteMany
  size: 2Gi
  storageClass: ""

